blank_issues_enabled: false
contact_links:
  - name: "â“ IRC"
    url: https://kiwiirc.com/nextclient/irc.freenode.net/?#jenkins-release
    about: Please ask and answer questions here, (#jenkins-release on freenode).
